baseurl = "https://smurphy000.github.io/"
title = "Conner Murphy"
theme = "digitalgarden"
languagecode = "en"
defaultcontentlanguage = "en"


[Params]
  description = "My Digital Garden on the Internet"
  images = ['/digital-garden-logo.png']
  enableSearch = true

# TODO - maybe newsletter could be a good idea in the future
# [Params.newsletter]
#   title = ""
#   description = "A curated weekly digest once a week to your mailbox"

#   # Supports buttondown, substack and revue
#   provider = "buttondown"

#   # Buttondown - URL from share page; Refer: https://blog.buttondown.email/2019/10/11/adding-a-buttondown-subscription-form-to-webflow#getting-your-subscription-url
#   # Substack - URL of the newsletter homepage; Example: https://on.substack.com/
#   # Revue - Username
#   path = "https://buttondown.email/api/emails/embed-subscribe/"


[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3
[[menu.main]]
  name = 'Portfolio'
  url = '/portfolio'
  weight = 4
[[menu.main]]
  name = 'Stack'
  url = '/stack'
  weight = 5
[[menu.main]]
  name = 'Links'
  params.header = true
  weight = 6


[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/Smurphy000'
  weight = 1
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/conner-murphy-4776b3148/'
  weight = 2

# [[menu.social]]
#   name = 'Twitch'
#   url = 'https://twitch.com'
#   weight = 7
# [[menu.social]]
#   name = 'Email'
#   url = 'mailto:user@example.org'
#   weight = 8
# [[menu.social]]
#   name = 'RSS'
#   url = '/articles/index.xml'
#   weight = 9


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true

