baseurl = "https://smurphy000.github.io/"
title = "Conner Murphy"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Conner Murphy"
  info = "Data Engineer"
  description = "Conner Murphy's portfolio and blog"
  keywords = "blog,developer,personal"
  
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  footercontent = ""
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2021

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = true

  customCSS = ["css/custom.css"]
  
  customJS = ["js/custom.js"]



# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/Smurphy000"
  target = "_blank"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/conner-murphy-4776b3148/"
  target = "_blank"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-stack-overflow fa-2x"
  weight = 1
  url = "https://stackoverflow.com/users/14072673/smurphy0000"
  target = "_blank"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Contact"
  weight = 4
  url = "contact/"
[[menu.main]]
  name = "Portfolio"
  weight = 3
  url = "portfolio/"
